<?php

return [
    
    'PORTFOLIO_IMAGE_URL' => 'uploads/portfolio',
    'POST_IMAGE_URL' => 'uploads/posts',
    'PORTFOLIO_FEATURED_IMAGE' => 'featured',
    'PORTFOLIO_GALLERY_IMAGES' => 'gallery',

    'STRIPE_MONTH_SILVER_PLAN_AMOUNT' =>  99 * 100,
    'STRIPE_MONTH_SILVER_PLAN_LABEL' =>  'Graphics Zoo Monthly Silver Plan',
    'STRIPE_MONTH_SILVER_PLAN_ID' =>  'M993D',
    'STRIPE_MONTH_SILVER_PLAN_TRIAL_PERIOD' =>  14,

    'STRIPE_MONTH_GOLDEN_PLAN_LABEL' =>  'Graphics Zoo Monthly Golden Plan',
    'STRIPE_MONTH_GOLDEN_PLAN_ID' =>  'M1991D',
    'STRIPE_MONTH_GOLDEN_PLAN_AMOUNT' =>  199 * 100,
    'STRIPE_MONTH_GOLDEN_PLAN_TRIAL_PERIOD' =>  14,

    'STRIPE_YEAR_SILVER_PLAN_LABEL' =>  'Graphics Zoo Yearly Silver Plan',
    'STRIPE_YEAR_SILVER_PLAN_ID' =>  'A893D',
    'STRIPE_YEAR_SILVER_PLAN_AMOUNT' =>  1068 * 100,
    'STRIPE_YEAR_SILVER_PLAN_TRIAL_PERIOD' =>  14,

    'STRIPE_YEAR_GOLDEN_PLAN_LABEL' =>  'Graphics Zoo Yearly Golden Plan',
    'STRIPE_YEAR_GOLDEN_PLAN_ID' =>  'A1791D',
    'STRIPE_YEAR_GOLDEN_PLAN_AMOUNT' =>  2148 * 100,
    'STRIPE_YEAR_GOLDEN_PLAN_TRIAL_PERIOD' =>  14,

    'POST_EXCERPT_TEXT_LIMIT' =>  105,
    'POST_EXCERPT_WORD_LIMIT' =>  125,   
    ];



